export enum Depths {
    POND_WATER,
    BG_TEXTURE,
    PATHWAY,
    DECOR_GREEN_DOTS,
    DECOR_GRASS,
    DECOR_STONKY,
    DECOR_PONDS,
    DECOR_SMALLBUSH,
    DECOR_BUSH,
    DECOR_ROCKS,
    BUILDINGS,
    CARRIER,
    FLY_TEXT,
    BUILD_ICON,
    UI,
    GRID_DEBUG
}
