export enum Events {
    UI_SHOP_TRY_PURCHASE = 'UI_SHOP_TRY_PURCHASE',
    CANCEL_BUILDING = 'CANCEL_BUILDING',
    PATHWAY_PLACED = 'PATHWAY_PLACED',
    CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS',
    UI_BUILDING_OPEN = 'UI_BUILDING_OPEN',
    UI_WAREHOUSE_OPEN = 'UI_WAREHOUSE_OPEN',
    UI_UNIT_OPEN = 'UI_UNIT_OPEN',
}
